spring:
  application:
    name: be
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/storepilot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:wjdgh01!!}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

storepilot:
  upload-dir: uploads

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
