package com.be.global.exception;

public enum ErrorCode {
    INVALID_EXCEL_FILE,
    INVALID_NAVER_CATEGORY_FILE,
    INVALID_MY_CATEGORY_MAPPING_FILE,
    CATEGORY_MATCHING_FAILED,
    COLUMN_NOT_FOUND,
    JOB_NOT_FOUND,
    JOB_NOT_COMPLETED,
    KEYWORD_GENERATION_FAILED,
    INTERNAL_SERVER_ERROR
}
